import type { GraphNode, GraphEdge, KnowledgeNode } from "@/domain/graph";
import {
	computeBusFactors,
	computeConfidences,
	computeAllMetrics,
} from "@/domain/metrics";
import { detectAllRisks } from "@/domain/risk-engine";
import { chatCompletion, getLlmConfig, type LlmConfig } from "./client";

// --- Wiki types ---

export interface WikiPage {
	nodeId: string;
	title: string;
	content: string; // markdown
	generatedAt: string;
}

export interface WikiIndex {
	pages: WikiPage[];
	tableOfContents: string;
	generatedAt: string;
}

// --- Heuristic wiki generator ---

function generatePageContent(
	node: GraphNode,
	nodes: GraphNode[],
	edges: GraphEdge[],
	busFactor: number,
	confidence: number,
	documented: boolean,
	expertNames: string[],
): string {
	const typeSection = `**Type:** ${node.type}`;
	const criticalityLine = (node as { criticality?: string }).criticality
		? `**Criticality:** ${(node as { criticality?: string }).criticality}`
		: "";

	const busFactorSection = `**Bus Factor:** ${busFactor} (${busFactor === 0 ? "⚠️ Lost knowledge" : busFactor === 1 ? "⚠️ Single point of failure" : "✅ Well distributed"})`;
	const confidenceSection = `**Confidence:** ${confidence}%`;
	const documentedSection = `**Documented:** ${documented ? "✅ Yes" : "❌ No — needs documentation"}`;

	let expertSection = "";
	if (expertNames.length > 0) {
		expertSection = `**Experts:** ${expertNames.join(", ")}`;
	} else {
		expertSection = "**Experts:** None at level ≥ 3 — ⚠️ Lost knowledge";
	}

	// Find related nodes
	const relatedEdges = edges.filter(
		(e) => e.fromNodeId === node.id || e.toNodeId === node.id,
	);
	const relatedLines = relatedEdges.map((e) => {
		const otherId = e.fromNodeId === node.id ? e.toNodeId : e.fromNodeId;
		const other = nodes.find((n) => n.id === otherId);
		const direction = e.fromNodeId === node.id ? "→" : "←";
		return `- ${direction} **${e.type}** → ${other?.name ?? otherId}`;
	});

	let timelineSection = "";
	if (node.type === "Knowledge") {
		const k = node as KnowledgeNode;
		timelineSection = [
			`**Knowledge Type:** ${k.knowledgeType ?? "unknown"}`,
			`**Validation State:** ${k.validationState ?? "proposed"}`,
		].join("\n");
	}

	let content = `# ${node.name}\n\n`;
	content += `${typeSection}\n`;
	if (criticalityLine) content += `${criticalityLine}\n`;
	content += `${busFactorSection}\n`;
	content += `${confidenceSection}\n`;
	content += `${documentedSection}\n`;
	if (expertSection) content += `${expertSection}\n`;
	if (timelineSection) content += `\n${timelineSection}\n`;
	content += `\n## Relationships\n\n`;
	content +=
		relatedLines.length > 0 ? relatedLines.join("\n") : "_No relationships._";
	content += `\n\n---\n_Generated by Company Brain OS AI Wiki Generator_`;

	return content;
}

function generateWikiHeuristic(
	nodes: GraphNode[],
	edges: GraphEdge[],
): WikiIndex {
	const busFactors = computeBusFactors(nodes, edges);
	const confidences = computeConfidences(nodes, edges);
	const knowledgeNodes = nodes.filter((n) => n.type === "Knowledge");

	const pages: WikiPage[] = knowledgeNodes.map((k) => {
		const bf = busFactors.find((b) => b.knowledgeId === k.id);
		const conf = confidences.find((c) => c.knowledgeId === k.id);
		const expertNames = (bf?.expertIds ?? []).map(
			(id) => nodes.find((n) => n.id === id)?.name ?? id,
		);

		return {
			nodeId: k.id,
			title: k.name,
			content: generatePageContent(
				k,
				nodes,
				edges,
				bf?.busFactor ?? 0,
				conf?.confidence ?? 0,
				bf?.documented ?? false,
				expertNames,
			),
			generatedAt: new Date().toISOString(),
		};
	});

	// Table of contents
	const toc = [
		"# Company Brain OS — Living Wiki",
		"",
		`${knowledgeNodes.length} knowledge areas documented.`,
		"",
		"## Knowledge Areas",
		...pages.map(
			(p, i) =>
				`${i + 1}. [${p.title}](#${p.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")})`,
		),
		"",
		"---",
		"_This wiki is generated from the live knowledge graph. Updated automatically._",
	].join("\n");

	return {
		pages,
		tableOfContents: toc,
		generatedAt: new Date().toISOString(),
	};
}

// --- Public API ---

export function generateWiki(
	nodes: GraphNode[],
	edges: GraphEdge[],
): WikiIndex {
	// Currently heuristic-only (LLM wiki generation would be expensive for large graphs).
	// LLM can be used for specific page enrichment in the future.
	return generateWikiHeuristic(nodes, edges);
}
